let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Casual Shirt",
    price: 45,
    desc: " Elevate your everyday style with this comfortable and versatile casual shirt. Perfect for any casual occasion..",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Office Shirt",
    price: 100,
    desc: "Make a lasting impression at work with this sharp and professional office shirt. Crafted for comfort and style.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "T Shirt",
    price: 25,
    desc: "Embrace casual comfort with this classic T-shirt. An essential addition to your wardrobe for laid-back days.",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mens Suit",
    price: 300,
    desc: "Look dashing and sophisticated in this impeccably tailored men's suit. Ideal for formal events and special occasions.",
    img: "images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Mens Tie",
    price: 25,
    desc: " Complete your formal look with this elegant men's tie. A stylish accessory that adds a touch of refinement.",
    img: "images/img-5.png",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Casual shoes",
    price: 200,
    desc: "  Step out in style and comfort with these trendy casual shoes. Perfect for everyday wear and leisure activities.",
    img: "images/img-6.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "black suit",
    price: 450,
    desc: "Make a bold statement with this sleek black suit. A timeless classic for formal affairs and evening events.",
    img: "images/img-7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "polo shirt",
    price: 45,
    desc: "Stay cool and stylish in this classic polo shirt. Versatile and comfortable, it's a must-have for your wardrobe.",
    img: "images/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "denim shirt",
    price: 85,
    desc: "Achieve a rugged yet stylish look with this denim shirt. Perfect for casual outings and relaxed gatherings.",
    img: "images/img-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "denim pants",
    price: 120,
    desc: "Embrace the durability and style of these denim pants. Ideal for a casual yet polished appearance.",
    img: "images/img-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "basic cap",
    price: 35,
    desc: "Top off your casual look with this basic cap. A simple and trendy accessory for outdoor adventures.",
    img: "images/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "leather boots",
    price: 350,
    desc:"Step into sophistication with these leather boots. Designed for durability and style, they're a statement piece.",
    img: "images/img-12.png",
  },
];
